### ISSUE TITLE
.NET Core 2.0 Coming Soon!

### ISSUE THREAD

**Issue by kitsun8** [BundledSticksInkorperated/Discore#10]
Just wanted to give you a heads up on this:
https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/

Seems like .NET Core/Standard  will be able to reference .NET Framework and wise versa in the near future. :) Can't wait to have more NuGet packages available!

Thanks for building Discore!

**Comment by Francessco121** [comment]
I'm really excited for this, Discore will definitely be moving to standard 2.0 once it's out of preview! We can leave this issue open until the upgrade if you'd like.

**Comment by kitsunen** [comment]
Sure, let's leave it open then :). 

I will be testing this Preview during this week, I think I will either go with .NET Framework Console App referencing Discore, or .NET Framework WinForms App referencing Discore.

I made a Overwatch tournament bot using Discore, and so far it has not crashed or went to exceptions even once, really impressed with Discore. What's great with 2.0, is that we can reference so much more NuGet packages now!

**Comment by Francessco121** [comment]
Looks like core and standard 2.0 are set to be released in Q3 of this year: https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates. Still a little ways off, but we're getting there.

**Comment by Francessco121** [comment]
.NET Core 2.0 and .NET Standard 2.0 are both here finally! In v4.0.0, Discore will target standard 2.0.

**Comment by Francessco121** [comment]
@kitsun8 If you're still interested in targeting 4.6.1, it looks like if your app uses .NET Core 2.0 it can now according to https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-platforms-support. So technically you wouldn't need to wait for Discore to move to standard 2.0 for this.

**Comment by kitsun8** [comment]
Thanks for the heads up! :) I will probably look into this later on, I'm swamped with updating bot functionality at the moment :I

**Comment by Francessco121** [comment]
Sure, on the 4.0.0 branch I've also already re-targeted Discore to standard 2.0 so...
