### ISSUE TITLE
Update to fully support v6 of the Discord API

### ISSUE THREAD

**Issue by Francessco121** [BundledSticksInkorperated/Discore#15]
Looks like v5 (which Discore currently operates on) will be deprecated soon: https://github.com/hammerandchisel/discord-api-docs/pull/293. Once the v6 documentation is complete, Discore should be updated as soon as possible.

**Edit:** v5 will be deprecated as of October 16, 2017, issues #16 and #17 have been created to address this issue, but neither will add full support for v6 (just enough to keep running).

**Comment by kitsun8** [comment]
Oh boy, wasn't aware of this at all. Do you think the update will be applied to both versions, 3 and 2?

If not, I will start making needed changes asap for my current projects!

Thanks in advance!

**Comment by Francessco121** [comment]
If needed, I can update 2.x as well, but it looks like this requires breaking changes for both 2.x and 3.x anyway...

**Comment by kitsun8** [comment]
Perhaps it is time for me to update to v3 anyway ;)

**Comment by Francessco121** [comment]
Okay so good news, after reviewing the changes made by version 6, I have determined that it is completely possible to patch both 2.x and 3.x **without any breaking changes**. Both patches *should* be released by the end of this weekend and have their own issues: #16 #17 .

The deprecation date for v6 was also pushed back a couple months (now October 16, 2017), which should give anyone using Discore plenty of time to update their nuget packages. Discore v3.0.0 and all releases below v2.4.1 will also be deprecated on this date.

However, since those patches won't be adding any functionality, they don't resolve this issue. For Discore to update fully to v6, 2 breaking changes would occur:

- `DiscordGuildChannelType` would be removed.
- `DiscordChannelType` would get completely new values.

And of course anything using those two enums would also have to change.

Right now I'm not entirely sure how to go about this. Following semantic versioning, this would bring us to Discore 4.0.0, but it feels wrong to already have another major release.

Any and all feedback is appreciated!

**Comment by Francessco121** [comment]
Just released v3.0.1 and v2.4.1 to bring internal support for v6.

**Comment by Francessco121** [comment]
I've decided that this issue will be solved across two releases:
**v3.1.0**: All additions that Gateway v6 brings that can be implemented without breaking changes.
**v4.0.0** All breaking changes/additions that will let Discore more accurately represent v6. This release will also have other things, but I don't have a finished plan yet.

#### What to expect in v3.1.0:
- `DiscordUserStatus.Invisible`
- `DiscordMessage.Type`
- `DiscordGuild.ApplicationId`

It's not much, but that's all that can be implemented without breaking stuff.

**Comment by Francessco121** [comment]
This is fixed on the 4.0.0 branch. :D
