### ISSUE TITLE
Change channel avatar

### ISSUE THREAD

**Issue by Flex1337** [BundledSticksInkorperated/Discore#28]
Hi, how can I change the channel avatar?
What I'm trying to do is not working.

**Comment by Francessco121** [comment]
Sorry, do you mean the server/guild icon? To change that you need to make a call to `DiscordHttpClient.ModifyGuild` and set the `Icon` property on the `ModifyGuildOptions` object you pass in.

Are you getting any errors? 

It would also be very helpful if you could post the code segment that isn't working.

**Comment by Francessco121** [comment]
Going to close this for now since it's been 16 days... If you still need help feel free to comment with more information.
