### ISSUE TITLE
Add CreateAt

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#38]
Hello, please add `CreateAt` to` Member`.
This is the date the account was created.

**Comment by Francessco121** [comment]
Unfortunately this is impossible as the API does not expose that information. 

Assuming you mean the date the *user* was created, [you can see here](https://discordapp.com/developers/docs/resources/user#user-object) that this property is not available. The closest thing to this is the date that the user joined the guild, [which is available on the member object](https://discordapp.com/developers/docs/resources/guild#guild-member-object).
