### ISSUE TITLE
Responding with a DirectMessage

### ISSUE THREAD

**Issue by kitsunen** [BundledSticksInkorperated/Discore#7]
Hello! Thank you for a great platform!
I am currently building a bot, and I'd like to be able to respond to users in a direct message. I'm a bit new with C#, so I couldn't find the required information straight away, so I thought to contact here.

For examples sake, lets say I was using the !ping listener, how would I begin forming the message as a DM, or does this function not yet exist?

Thanks!

**Comment by Francessco121** [comment]
Going off of the example bot from the README, responding to DM's actually already works. In the example, we are grabbing the channel that the message was created in as an `ITextChannel`. `ITextChannel` represents the common functionality between DM channels and guild text channels.

Of course you can also limit the code to only respond to DM's. One way would be to check `ITextChannel.ChannelType` before responding to see if it's equal to `DiscordChannelType.DirectMessage`. 

Another option is casting the result from the cache to a `DiscordDMChannel`, for example:

```csharp
DiscordDMChannel dm = shard.Cache.Channels.Get(message.ChannelId) as DiscordDMChannel;
if (dm != null)
{
    dm.CreateMessage("Hello!");
}
```

Hope this helps! Also if you haven't seen it, we do have a wiki [over here](https://github.com/BundledSticksInkorperated/Discore/wiki).

**Comment by kitsunen** [comment]
Sure opens it up a bit :) Thank you, I'm currently reading through your docs.

Actually I went off explaining the wrong way, sorry for that.
What if I wanted to answer !command in a chat channel as a DM to the user that invoked the !command?

Sorry for making such trouble.

**Comment by Francessco121** [comment]
So what you're trying to do (and correct me if I'm wrong) is receive a message via a guild channel, and respond to the user who created that message through a DM?

Currently the only way to do this is through an HTTP call. Assuming the message object is named `msg` and your `DiscordWebSocketApplication` is named `app` you would want to do:

```csharp
DiscordDMChannel dm = await app.HttpApi.Users.CreateDM(msg.Author.Id);
```

That `DiscordDMChannel` will be between your bot and the user who created the message.

I should probably make a wiki entry for this :)

**Comment by kitsunen** [comment]
Thank you so much! I will try this out today. :) :+1:
